name: Java CI with Maven

on:
  push:
    branches:
      - deploy-CI

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Build with Maven
        run: mvn -B test
        env:
          MAVEN_OPTS: '-Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository'
        with:
          maven-version: '3.9.6'